import dotenv from 'dotenv';
dotenv.config();

const config = Object.freeze({
  PORT: process.env.PORT,
  DB_URL: process.env.DB_URL,
  NODE_ENV: process.env.NODE_ENV,

  GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY,
  GEMINI_API_KEY: process.env.GEMINI_API_KEY,
  APIFY_TOKEN: process.env.APIFY_TOKEN,
  APIFY_ZILLOW_ACTOR_ID: process.env.APIFY_ZILLOW_ACTOR_ID,
  APIFY_REDFIN_ACTOR_ID: process.env.APIFY_REDFIN_ACTOR_ID,
  APIFY_REALTOR_ACTOR_ID: process.env.APIFY_REALTOR_ACTOR_ID,
  APIFY_MLS_ACTOR_ID: process.env.APIFY_MLS_ACTOR_ID,
  APIFY_COUNTY_ACTOR_ID: process.env.APIFY_COUNTY_ACTOR_ID,
  APIFY_PROPERTY_DETAIL_ACTOR_ID: process.env.APIFY_PROPERTY_DETAIL_ACTOR_ID,
  ZENROWS_API_KEY: process.env.ZENROWS_API_KEY,
  ADDRESS_NORMALIZE_URL: process.env.ADDRESS_NORMALIZE_URL,
  SCRAPPER_API_KEY: process.env.SCRAPPER_API_KEY,
  RESET_PASSWORD_URL: process.env.RESET_PASSWORD_URL,
  SET_PASSWORD_URL: process.env.SET_PASSWORD_URL,

  ACCESS_TOKEN_NAME: process.env.ACCESS_TOKEN_NAME,
  ACCESS_TOKEN_EXPIRY: process.env.ACCESS_TOKEN_EXPIRY,
  ACCESS_TOKEN_MAX_AGE: process.env.ACCESS_TOKEN_MAX_AGE,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_NAME: process.env.REFRESH_TOKEN_NAME,
  REFRESH_TOKEN_EXPIRY: process.env.REFRESH_TOKEN_EXPIRY,
  REFRESH_TOKEN_MAX_AGE: process.env.REFRESH_TOKEN_MAX_AGE,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,

  CLOUDINARY_CLIENT_NAME: process.env.CLOUDINARY_CLIENT_NAME,
  CLOUDINARY_CLIENT_KEY: process.env.CLOUDINARY_CLIENT_KEY,
  CLOUDINARY_CLIENT_SECRET: process.env.CLOUDINARY_CLIENT_SECRET,
  CLOUDINARY_FOLDER_NAME: process.env.CLOUDINARY_FOLDER_NAME,

  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,

  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  SENDGRID_MAIL_FROM: process.env.SENDGRID_MAIL_FROM,

  VERIFICATION_TOKEN_SECRET: process.env.VERIFICATION_TOKEN_SECRET,
  VERIFICATION_TOKEN_EXPIRY: process.env.VERIFICATION_TOKEN_EXPIRY,
  FONTS_PATH: process.env.FONTS_PATH,
});

const getEnv = (key) => {
  const value = config[key];
  if (!value) throw new Error(`Env variable ${key} is not defined`);
  return value;
};
export { getEnv };
